version: "3.4"
services:
  tp3:
    image: nginx
    ports:
      - 9000:80
    volumes:
      - ./TP3:/usr/share/nginx/html:ro
    restart: always

    
  labo11-web:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./labo11:/usr/share/nginx/html:ro
    restart: always