
services:
  tp3:
    image: nginx
    ports:
      - 9000:80
    volumes:
      - ./TP3/Atlas/app/equipe-UMBA-TATIANA:/usr/share/nginx/html:ro
    restart: always

  labo10-web:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./labo10:/usr/share/nginx/html:ro
    restart: always

  labo11-web:
    image: nginx
    ports:
      - 7000:80
    volumes:
      - ./labo11:/usr/share/nginx/html:ro
    restart: always